// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DataModels.Base;
using System;
using System.Collections.Generic;

namespace DataModels.Models;

public partial class OrderDeatil:BaseClass
{

    public string OrderId { get; set; }

    public string ProductId { get; set; }

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal Subtotal { get => Quantity * UnitPrice; }

    public virtual Order? Order { get; set; }

    public virtual Product? Product { get; set; }
}