// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DataModels.Base;
using System;
using System.Collections.Generic;

namespace DataModels.Models;

public partial class Order : BaseClass
{


    public string CustomerId { get; set; }

    public float TotalAmount { get; set; }

    public string OrderStatus { get; set; }

    public virtual User? Customer { get; set; }
    public virtual ICollection<OrderDeatil>? OrderDeatils { get; set; } = new List<OrderDeatil>();
}